# Generated by Django 3.1.7 on 2021-04-09 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('authentication', '0002_auto_20210313_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resta_name', models.CharField(max_length=50)),
                ('has_AC', models.BooleanField(default=False)),
                ('has_delivery', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('resta_contact', models.CharField(max_length=10)),
                ('resta_address', models.CharField(max_length=150)),
                ('resta_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.serviceprovider')),
                ('resta_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.place')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fooditem_name', models.CharField(max_length=20)),
                ('food_type', models.CharField(max_length=10)),
                ('food_cost', models.IntegerField()),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
        ),
    ]
