# Generated by Django 3.1.7 on 2021-05-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20210503_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='food_cost',
            field=models.IntegerField(default=0),
        ),
    ]
