# Generated by Django 3.1.7 on 2021-05-06 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0003_auto_20210503_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='resta_image',
            field=models.ImageField(default=True, upload_to='pics/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='resta_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
