# Generated by Django 3.1.7 on 2021-05-06 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0002_hotel_hotel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_img',
            field=models.ImageField(default=True, upload_to='pics/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
