# Generated by Django 3.1.7 on 2021-04-10 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction_name', models.CharField(default='Attraction', max_length=50)),
                ('attraction_type', models.CharField(default='attracttion', max_length=50)),
                ('attraction_description', models.CharField(default='Place to visit', max_length=50)),
                ('attraction_place', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='hotels.place')),
            ],
        ),
    ]
