# Generated by Django 3.1.7 on 2021-04-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='attraction_img',
            field=models.ImageField(default=0, upload_to='Images/'),
            preserve_default=False,
        ),
    ]
