# Generated by Django 3.1.7 on 2021-04-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitplace', '0002_attractions_attraction_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='attraction_description',
            field=models.CharField(default='Place to visit', max_length=500),
        ),
    ]
