# Generated by Django 3.1.7 on 2021-05-06 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShoppingComplex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcomplex',
            name='shoppingcomplex_sp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
