# Generated by Django 3.1.7 on 2021-04-14 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('authentication', '0002_auto_20210313_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=25)),
                ('shop_address', models.CharField(max_length=100)),
                ('shop_contactinfo', models.CharField(max_length=10)),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.serviceprovider')),
                ('shop_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.place')),
            ],
        ),
    ]
