# Generated by Django 3.1.6 on 2021-04-30 15:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_auto_20210416_1549'),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinemahall_name', models.CharField(max_length=50)),
                ('seats', models.CharField(max_length=5)),
                ('timing', models.CharField(max_length=100)),
                ('cinemahall_address', models.CharField(max_length=100)),
                ('cinemahall_contactinfo', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('current_movie', models.CharField(max_length=50)),
                ('cinemahall_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.place')),
                ('theatre_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.serviceprovider')),
            ],
        ),
    ]
